name: ${COMPOSE_PROJECT_NAME:-genghis-routing}

services:
  web:
    image: ${REGISTRY:-ghcr.io}/${IMAGE_PREFIX:-genghis-routing}/web:${IMAGE_TAG:-latest}
    container_name: ${CONTAINER_NAME_PREFIX:-genghis-routing}-web
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - proxy_net
    profiles:
      - web


networks:
  proxy_net:
    external: true
